version: '3'

services:
  api:
    build: .
    container_name: api
    restart: always
    volumes:
      - ~/logs:/root/logs
    ports:
      - 7001:7001

## docker-compose up -d --build
## docker logs api
